// lib/calendar/exportQuarterlyIcs.ts
import { isUnlocked } from "@/lib/access/accessState";

export type QuarterlyScheduleItem = {
  quarter: string;      // "Q1", "Q2", etc
  due: string;          // e.g. "April 15, 2025" (human-readable)
  amount: number;       // per-quarter payment amount
};

type AccessState = {
  hasPaidForPlan?: boolean;
  filingClient?: boolean;
};

/** Pad 2 digits */
function pad2(n: number) {
  return String(n).padStart(2, "0");
}

/** Convert Date => ICS date-only YYYYMMDD */
function formatDateToIcsDateOnly(date: Date) {
  const y = date.getFullYear();
  const m = pad2(date.getMonth() + 1);
  const d = pad2(date.getDate());
  return `${y}${m}${d}`;
}

/** Convert Date => UTC timestamp YYYYMMDDTHHMMSSZ */
function formatUtcStamp(date: Date) {
  const y = date.getUTCFullYear();
  const m = pad2(date.getUTCMonth() + 1);
  const d = pad2(date.getUTCDate());
  const hh = pad2(date.getUTCHours());
  const mm = pad2(date.getUTCMinutes());
  const ss = pad2(date.getUTCSeconds());
  return `${y}${m}${d}T${hh}${mm}${ss}Z`;
}

/** Add days */
function addDays(date: Date, days: number) {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

/** If Sat/Sun, push to Monday */
function adjustWeekend(date: Date) {
  const d = new Date(date);
  const day = d.getDay(); // 0=Sun, 6=Sat
  if (day === 6) return addDays(d, 2); // Sat -> Mon
  if (day === 0) return addDays(d, 1); // Sun -> Mon
  return d;
}

/** Escape text per RFC5545 */
function escapeIcsText(input: string) {
  return input
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\r\n/g, "\\n")
    .replace(/\n/g, "\\n");
}

function formatMoney(n: number) {
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

/**
 * Exports an .ics calendar file for IRS quarterly estimated tax payments.
 * - Locked: titles show LOCKED PREVIEW, dates only (no amounts)
 * - Unlocked: includes payment amounts + guidance
 */
export function exportQuarterlyIcs({
  schedule,
  taxYear,
  access,
}: {
  schedule: QuarterlyScheduleItem[];
  taxYear: number;
  access: AccessState;
}) {
  const unlocked = isUnlocked(access);

  const nowStamp = formatUtcStamp(new Date());
  const payUrl = "https://www.irs.gov/payments";

  const lines: string[] = [];
  lines.push("BEGIN:VCALENDAR");
  lines.push("VERSION:2.0");
  lines.push("CALSCALE:GREGORIAN");
  lines.push("METHOD:PUBLISH");
  lines.push("PRODID:-//SW Tax Service//IRS Quarterly Estimated Taxes//EN");

  for (const item of schedule) {
    const raw = new Date(item.due);
    const dueDate = adjustWeekend(raw);

    const start = formatDateToIcsDateOnly(dueDate);
    const end = formatDateToIcsDateOnly(addDays(dueDate, 1)); // all-day events end next day

    const amountText = unlocked ? ` (${formatMoney(item.amount)})` : "";
    const summary = unlocked
      ? `IRS Estimated Tax Payment Due — ${item.quarter}${amountText}`
      : `LOCKED PREVIEW — IRS Estimated Tax Due — ${item.quarter}`;

    const description = unlocked
      ? [
          `Tax year: ${taxYear}`,
          `Quarter: ${item.quarter}`,
          `Estimated payment amount: ${formatMoney(item.amount)}`,
          "Form: 1040-ES (Estimated Tax)",
          `Pay online: ${payUrl}`,
          "",
          "Generated by SW Tax Service.",
          "This is not an official IRS notice.",
        ].join("\n")
      : [
          `Tax year: ${taxYear}`,
          `Quarter: ${item.quarter}`,
          "Form: 1040-ES (Estimated Tax)",
          "Preview file: payment amounts are locked until you unlock your full tax plan.",
          `Pay online: ${payUrl}`,
          "",
          "Generated by SW Tax Service.",
        ].join("\n");

    const uid = `swts-${taxYear}-${item.quarter}-${start}@swtaxservice.com`;

    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${escapeIcsText(uid)}`);
    lines.push(`DTSTAMP:${nowStamp}`);
    lines.push(`DTSTART;VALUE=DATE:${start}`);
    lines.push(`DTEND;VALUE=DATE:${end}`);
    lines.push(`SUMMARY:${escapeIcsText(summary)}`);
    lines.push(`DESCRIPTION:${escapeIcsText(description)}`);
    lines.push(`URL:${payUrl}`);
    lines.push("TRANSP:TRANSPARENT");
    lines.push("CATEGORIES:Taxes,Estimated Tax");

    // Reminder 7 days before
    lines.push("BEGIN:VALARM");
    lines.push("TRIGGER:-P7D");
    lines.push("ACTION:DISPLAY");
    lines.push(`DESCRIPTION:${escapeIcsText("Estimated tax payment reminder")}`);
    lines.push("END:VALARM");

    lines.push("END:VEVENT");
  }

  lines.push("END:VCALENDAR");

  const ics = lines.join("\r\n"); // CRLF for best calendar compatibility

  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = unlocked
    ? `IRS-Quarterly-Estimated-Taxes-${taxYear}.ics`
    : `IRS-Quarterly-Estimated-Taxes-PREVIEW-${taxYear}.ics`;

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
